i18n/miraheze/es.json

Addition of "right-managewiki-restricted" for "managewiki-restricted" right description. I forgot to add it in the previous patch, sorry. I request your merger. Thanks.

Addition of "right-managewiki-restricted"

---

includes/MirahezeMagicHooks.php

properly handle spaces, as well as allow for [[mh:wiki]] to link to that wiki

fixes for global interwiki

---

extension.json
includes/MirahezeMagicHooks.php

This would allow for users to interwiki to Miraheze, but not need to setup an interwiki for all Miraheze wikis.
For example if they had `miraheze:` as `https://meta.miraheze.org/wiki/$1`, they would be able to use `[[miraheze:mh:test:Example]]` to access `https://test.miraheze.org/wiki/Example`.

Hard redirects all pages like Mh:Wiki:Page as global interwiki

---

includes/MirahezeMagicHooks.php

Special:CentralAutoLogin/setCookies (required for login) won't work with the current system, but should when checking the root title instead

check root title against special pages

---

i18n/overrides/en.json
includes/MirahezeMagicHooks.php

The current messages don't make sense in our context. CA is global so globally overriding.

Miraheze-ifying ca admin merge message

---

maintenance/removePII.php

Adds a extra layer of protection to make sure this ip is removed.

Set echo_event.event_agent_ip to null regardless if it is already null

---

includes/MirahezeMagicHooks.php

Fixes an issue where renaming a private wiki doesn't rename its static directory.
Also adds a check to make sure sitemaps directory exists before removing it (if switching to private mode).

Fix renaming private wikis directory

---

includes/MirahezeMagicHooks.php

Reverts this commit (https://github.com/miraheze/mw-config/commit/24b75ad4dc9141fe46723d1d7f370d2d01feb7b3); no pre-existing consensus for this whitelisting on all private wikis. Discussed with @JohnFLewis and @MacFan4000 on IRC

Remove Special:Interwiki from whitelisted special pages

---

includes/MirahezeMagicHooks.php

it has 3 params but only 2 are really usable. Its not a select query so we don't need "*".

MirahezeMagicHooks::onCreateWikiDeletion: Fix param for dbw->delete

---

maintenance/removePII.php

Since these now use actors, and actors always remain the same, these can be removed.

Remove Comments user columns from RemovePII (T6961)

---

extension.json
includes/MirahezeMagicHooks.php

Prevents AbuseFilter from applying to the `autocreateaccount` action.

Avoid filtering automatic account creation

---

extension.json
includes/MirahezeMagicHooks.php
includes/MirahezeMagicLogEmailManager.php
includes/ServiceWiring.php

Untested proof of concept. Expected to work like this:
```php
$wgAvailableRights[] = 'watched-person';
$wgMirahezeMagicLogEmailConditions = [
[
'right' => 'watched-person',
'email' => 'watchers@shadycorp.invalid',
],
];
```

Add email notifications on privileged actions

---

includes/MirahezeMagicLogEmailManager.php
includes/ServiceWiring.php

Note the renamed setting key ('right' to 'group')﻿

LogEmail: Use global groups instead of rights

---

includes/MirahezeMagicHooks.php

Per discussion with @Reception123, and also @RhinosF1, on IRC following https://phabricator.miraheze.org/T7257, which reminded me of this commit I wanted to make. As these pages are essential for users managing their own private data, which is copied to local wikis, it's essential they have access to these pages to do this. This should, in turn, allow them to disable their own notifications, I think, as the former is likely the missing link. In the latter case, MediaWiki adds one's own user page to their watchlist automatically by default on attaching one's account and there's no way to disable it (that is, you can disable watchlisting pages you edit, but not this). In any case, it's fine because either the user was a former `member` and wants to remove the pages from their watchlist to …

Whitelist Special:Preferences and Special:Watchlist

---

includes/MirahezeMagicHooks.php

Should maintain compatibility with 1.35 for now.

fix AbuseFilterShouldFilterAction hook for 1.36 and add notes

---

maintenance/rebuildVersionCache.php

1) Supports ExtensionRegistry
2) Supports all extensions, even ones disabled on the specified wiki, since gitinfo cache is shared it should rebuild on all extensions and skins.
* ~~This may make this script work without the core hack from miraheze/mediawiki#2289.~~ It does not, but this is still needed.

RebuildVersionCache: Support rebuilding for all extensions

---

ReCaptchaNoCaptcha/includes/ReCaptchaHtml.php
ReCaptchaNoCaptcha/includes/ReCaptchaNoCaptcha.php
ReCaptchaNoCaptcha/includes/ReCaptchaNoCaptchaHooks.php

Reverts miraheze/MirahezeMagic#300
recaptcha.net does not work.
We should only fall back if google is broken and not returning a response, maybe we can use v2 in China only?

Revert "reCAPTCHA: use globally not-blocked recaptcha.net instead of google.com"

---

i18n/miraheze/en.json
i18n/miraheze/qqq.json

Required because of more contemporary changes to the Navigation Popups gadget on English Wikipedia that uses localised group names, rather than technical group names. I started a discussion to possibly revert the change (https://en.wikipedia.org/w/index.php?title=MediaWiki_talk:Gadget-popups.js&oldid=1055257786#Question_about_possible_recently_deployed_changes_to_Navigation_Popups_gadget), but it seems unlikely to pass
I know I need to do the `qqq.json` part, @Universal-Omega

Add group member interface message for the member group

---

includes/MirahezeMagicHooks.php

Always using database on every page load causes connection timed out errors.
Evidenced by:
```
mediawiki_error
:real_connect(): (HY000/2002): Connection timed out
```
With the following being the part of the stack trace that leads to error:
```
#9 /srv/mediawiki/w/extensions/CreateWiki/includes/RemoteWiki.php(34): wfGetDB(integer, array, string)
#10 /srv/mediawiki/w/extensions/MirahezeMagic/includes/MirahezeMagicHooks.php(436): Miraheze\CreateWiki\RemoteWiki->__construct(string)
#11 /srv/mediawiki/w/includes/HookContainer/HookContainer.php(338): MirahezeMagicHooks::onSiteNoticeAfter(string, SkinVector)
```

use CW config variables for SiteNoticeAfter --

---

maintenance/assignImportedEdits.php

* Only update tables if there is rows to update
* Drop revision_actor_temp support, and use revision for actor migration (T8982)

Improve AssignImportedEdits

---

includes/MirahezeMagicHooks.php

Removes usage of the `wfShouldEnableSwift()` function.

Always use Swift for renames and deletions

---

i18n/overrides/en.json
includes/MirahezeMagicHooks.php

WebAuthn authenticators only work on the specific domain where they were registered. So, registering it on for example avid.miraheze.org, one may find themselves surprised that they are not able to log-in at Meta if they don't know how WebAuthn works.
Like in Wikimedia, we may want to warn users regarding this behavior. Once logged in on the wiki where they registered the authenticator, CentralAuth should take care of the rest and log them in on all the various wikis as they browse.

Add a warning regarding where to register the authenticator

---

maintenance/rebuildVersionCache.php

wgBaseDirectory was added in core as a temporary alternative to the non-wg prefixed `$IP` but in practice neither is preferred given the MW_INSTALL_PATH constant.
Use it here as well, matching other parts of the same file that use it here already.

rebuildVersionCache: Use MW_INSTALL_PATH instead of wgBaseDirectory

---

includes/SpecialVanishUser.php

Renameuser is now bundled into core and thus the extension is of no use.

Don't trigger Status::newFatal( 'centralauth-rename-notinstalled' ) on mw 1.40+

---

extension.json
includes/Specials/SpecialVanishUser.php

* Reverts #429 but uses optional_services instead to prevent fataling on non-CentralAuth wikis

Inject CentralAuth services again

---

i18n/managewiki/en.json

The word "function" is already mentioned,
and those magic words return wikitext and
not other functions
(it's just wikitext and not JavaScript ;).

Improve the message managewiki-setting-wgAllowSlowParserFunctions-help

---

maintenance/generateExtensionDatabaseList.php

The result of this script is pretty useless as it is if we want to count the number of wikis that use an extension quickly because at current its all on one line. 
This pretty prints it using JSON_PRETTY_PRINT so the result can be piped to wc -l

Pretty Print JSON result

---

includes/Hooks.php

The signatures will change (type hinting) and we don't want to go down in the process so lets remove the interfaces for now.

Temporarily remove CreateWiki hook interfaces

---

extension.json
includes/HookHandlers/Main.php

Indicate a Miraheze wiki in the query api siteinfo general info. This allows to easily identify even custom domain Miraheze wikis though the MW api.
https://meta.miraheze.org/w/api.php?action=query&meta=siteinfo

add Miraheze key to APIQuerySiteInfoGeneralInfo

---

includes/HookHandlers/CreateWiki.php
maintenance/CheckWikiDatabases.php

This is needed to make GlobalContributions work. If there are unknown databases in this field, then it breaks GlobalContributions.

Add support for CheckUser global table
