miraheze/MirahezeMagic

- i18n/miraheze/ko.json
- i18n/overrides/ko.json
- Korean translation
- Miraheze is left untranslated since I couldn't find appropriate translation for it.
> Korean translation

- i18n/miraheze/fr.json
> add french translation

- i18n/miraheze/es.json
Addition of Spanish Translation for Close Wiki Mail. Thanks.
> Addition of Spanish Translation for Close Wiki Mail

- i18n/miraheze/es.json
Addition of "translator" and "translationadmin" in Spanish. Thanks.
> Addition of "translator" and "translationadmin" (Spanish Translation)

- i18n/miraheze/es.json
Reverts miraheze/MirahezeMagic#37 per #39
> Revert "Addition of "translator" and "translationadmin" (Spanish Translation)"

- extension.json
- includes/MirahezeMagicHooks.php
- maintenance/addWikiToServices.php
This will be used to generate services yaml syntax for parsoid and other services.
> Add addWikiToServices script to generate our services yaml file

- extension.json
- includes/GlobalNewFiles/GlobalNewFilesHooks.php
This will remove files that are being deleted from the gnf_files table.
> GlobalNewFiles: Use FileDeleteComplete hook

- includes/MirahezeMagicHooks.php
getRootTitle doesn't work in the Special namespace, so, just hard code it in
> fix checking root pages

- i18n/managewiki/en.json
If you want to contribute, leave me a note - sets up i18n for mw/settings
> Add translations per T4370

- i18n/overrides/en.json
updating i18n
Will merge soon once I've logged into the server
> Update i18n T4735

- includes/GlobalNewFiles/GlobalNewFilesPager.php
> GlobalNewFile: Fix ordering by timestamp

- i18n/overrides/en.json
- i18n/overrides/qqq.json
- includes/MirahezeMagicHooks.php
Upstream fix could be a while, deploying farm-wide fix
> Add overrides to avoid missing i18n

- includes/GlobalNewFiles/GlobalNewFilesPager.php
> Replace deprecated isAllowed(...) with userHasRight(...)

- maintenance/removePII.php
Note that if you run foreachwikiindblist, you will need to do the escaping your self as it removes everything if it has a space (leaving just the first part of the name).
> Automatically convert space into _

- maintenance/removePII.php
Also show status error if user page fails to be deleted.
> Fix deleting user pages

- extension.json
- includes/MirahezeMagicHooks.php
> Use MimeMagicInit hook

- maintenance/sendBulkEmails.php
Also update script to commit https://github.com/wikimedia/mediawiki-extensions-WikimediaMaintenance/commit/5dea52d964b19cb70df0bf4032b3d9cc39a0bbd0
> sendBulkEmails does not need to depend on WikimediaMaintenance

- py/generateSitemapIndex.py
Do things in a more "pythonic" way
Write to the file all at once (possible bug fix)
Remove use of while loops and fix mistaken treatment of for loops as while loops
> Improve script

- includes/MirahezeIRCRCFeedFormatter.php
Updates to match some of https://raw.githubusercontent.com/wikimedia/mediawiki/REL1_34/includes/rcfeed/IRCColourfulRCFeedFormatter.php
> MirahezeIRCRCFeedFormatter: Slightly cleanup a bit

- maintenance/populateWikibaseSitesTable.php
Reverts miraheze/MirahezeMagic#131
> Revert "Revert "If a wiki dbname is larger then 32, ignore it""

- maintenance/addWikiToServices.php
Reverts miraheze/MirahezeMagic#168
> Revert "Services: remove VE+Flow as now using Parsoid/PHP"

- maintenance/addWikiToServices.php
Reverts miraheze/MirahezeMagic#169
> Revert "Revert "Services: remove VE+Flow as now using Parsoid/PHP""

- extension.json
- includes/SpecialRedirectSitemap.php
Reverts miraheze/MirahezeMagic#179
> Revert "Remove  SpecialRedirectSitemap"

- maintenance/generateMirahezeSitemap.php
> Fix  domain for --server in generateSitemap

- includes/MirahezeIRCRCFeedFormatter.php
Done to fix Hooks::run to be Hooks::runner
> Bring up-to-date with IRCColourfulRCFeedFormatter

- includes/MirahezeMagicHooks.php
https://github.com/wikimedia/mediawiki/blob/5a2f573ab52a4920876d58dd3720c8985679d97c/includes/user/User.php#L3075
> Use User::isRegistered instead of User::isLoggedIn

- i18n/overrides/en.json
- includes/MirahezeMagicHooks.php
> Remove datadump-desc

- i18n/miraheze/en.json
- i18n/miraheze/qqq.json
For [T7125](https://phabricator.miraheze.org/T7125#141452)
> Add i18n for Special:ManageWiki/extensions tabs

- maintenance/removePII.php
> removePII: Remove PII data from CheckUser

- maintenance/rebuildVersionCache.php
Also fixes [T7733](https://phabricator.miraheze.org/T7733).
> Add option to rebuildVersionCache for using the mediawiki-staging directory

- .github/workflows/globals.php
Reverts miraheze/MirahezeMagic#342
> Revert "CI: replace use of deprecated wfGetDB with LoadBalancer"

- includes/SpecialMirahezeSurvey.php
> Update MirahezeSurvey modules

- maintenance/fixImageUser.php
Drop revision_actor_temp support, and use revision for actor migration (T8982)
> fixImageUser: support actor migration

- maintenance/fixUserIdRevision.php
Drop revision_actor_temp support, and use revision for actor migration (T8982)
> fixUserIdRevision: support actor migration

- maintenance/createUsers.php
Drop revision_actor_temp support, and use revision for actor migration (T8982)
> createUsers: use revision table

- maintenance/assignImportedEdits.php
- maintenance/createUsers.php
- maintenance/fixImageUser.php
- maintenance/fixUserIdLogging.php
- maintenance/fixUserIdRevision.php
- maintenance/generateExtensionDatabaseList.php
- maintenance/generateMirahezeSitemap.php
- maintenance/resetWikiCaches.php
> Don't use Maintenance::$mDescription directly

- includes/MirahezeMagicHooks.php
> Replace usages of Skin::footerLink

- maintenance/assignImportedEdits.php
- maintenance/createUsers.php
- maintenance/fixImageUser.php
- maintenance/fixUserIdLogging.php
- maintenance/fixUserIdRevision.php
- maintenance/generateExtensionDatabaseList.php
- maintenance/generateManageWikiBackup.php
> maintenance: replace usages of wfGetDB

- includes/MirahezeMagicHooks.php
- maintenance/generateManageWikiBackup.php
- maintenance/generateMirahezeSitemap.php
- py/generateSitemapIndex.py
> Add support for Swift

- includes/MirahezeIRCRCFeedFormatter.php
Only change is to use MainConfigNames.
> Update MirahezeIRCRCFeedFormatter from upstream

- includes/MirahezeMagicHooks.php
Per conversation with two Stewards, Agent Isai, and Reception123.
> Whitelist Special:Interwiki if having the interwiki right

- maintenance/createCargoDB.php
script will be used for creating an isolated cargo DB for the wiki when enabling the extension
intended for use with https://github.com/miraheze/mw-config/pull/5182
> create maintenance script createCargoDB.php

- maintenance/rebuildVersionCache.php
This is untested, it should not cause any fatals now (noting that I couldn't reproduce fatals elsewhere outside Miraheze even enabling same extensions fatals were for), but it should also be confirmed to properly update gitinfo cache, and that commit ID, and data, etc... appear properly on Special:Version after clearing gitinfo cache once for testing.
> RebuildVersionCache: remove usage of ExtensionProcessor

- .github/workflows/python.yml
> Test against python 3.11

- i18n/managewiki/en.json
This option allows editing wikitext, not just reading.
> Fix wgVisualEditorEnableWikitext description

- i18n/overrides/en.json
Remove comma splice and make some other small improvements for readability.
> Rephrase miraheze-requestwiki-info-guidance-post

- includes/MirahezeIRCRCFeedFormatter.php
Just override what we actually change so that it is less to maintain
> MirahezeIRCRCFeedFormatter: simplify

- maintenance/rebuildVersionCache.php
This is an argument so we have to set that option to true.
> rebuildVersionCache: Fix setting --version

- includes/HookHandlers/Main.php
Needed for miraheze/CreateWiki#695
> Update CreateWiki maintenance script format

- i18n/miraheze/en.json
- i18n/miraheze/qqq.json
> Remove specialpages-group-wikimanage from i18n

- maintenance/PopulateWikibaseSitesTable.php
Fixes [T13716](https://issue-tracker.miraheze.org/T13716)
> Update PopulateWikibaseSitesTable for new WikiDiscover API

- includes/HookHandlers/ImportDump.php
Hooks are now type hinted and ImportDumpRequestManager is renamed to RequestManager.
> Update ImportDump hooks
